# Generated by Django 4.0.4 on 2022-05-23 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_weatherinfo_base',
            fields=[
                ('city', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='地市')),
                ('province', models.CharField(max_length=5, verbose_name='省份')),
                ('weather', models.CharField(max_length=5, verbose_name='天气现象')),
                ('temperature', models.CharField(max_length=5, verbose_name='实时气温')),
                ('winddirection', models.CharField(max_length=5, verbose_name='风向')),
                ('windpower', models.CharField(max_length=5, verbose_name='风力级别')),
                ('humidity', models.CharField(max_length=3, verbose_name='空气湿度')),
                ('reporttime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据发布的时间')),
            ],
            options={
                'verbose_name_plural': '当前天气',
            },
        ),
        migrations.CreateModel(
            name='DB_weatherinfo_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=5, verbose_name='地市')),
                ('province', models.CharField(max_length=5, verbose_name='省份')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('week', models.CharField(max_length=1, verbose_name='星期')),
                ('dayweather', models.CharField(max_length=5, verbose_name='白天天气')),
                ('nightweather', models.CharField(max_length=5, verbose_name='晚上天气')),
                ('daytemp', models.CharField(max_length=5, verbose_name='白天气温')),
                ('nighttemp', models.CharField(max_length=5, verbose_name='晚上气温')),
                ('daywind', models.CharField(max_length=5, verbose_name='白天风向')),
                ('nightwind', models.CharField(max_length=5, verbose_name='晚上风向')),
                ('daypower', models.CharField(max_length=5, verbose_name='白天风力')),
                ('nightpower', models.CharField(max_length=5, verbose_name='晚上风力')),
                ('reporttime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据发布的时间')),
            ],
            options={
                'verbose_name_plural': '未来天气',
                'unique_together': {('city', 'date')},
            },
        ),
    ]
