# Generated by Django 4.0.4 on 2022-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernam', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('openid', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信的openid')),
                ('unionid', models.CharField(blank=True, max_length=36, null=True, verbose_name='微信的unionid')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信昵称')),
                ('province', models.CharField(blank=True, max_length=10, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=10, null=True, verbose_name='地市')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='国家')),
                ('avatarurl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='头像url')),
                ('sex', models.CharField(blank=True, max_length=1, null=True, verbose_name='性别')),
                ('qq', models.CharField(blank=True, max_length=15, null=True, verbose_name='qq')),
                ('weixin', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信号')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('type', models.CharField(blank=True, max_length=1, null=True, verbose_name='用户类型(0:网站，1：微信,2：qq')),
            ],
        ),
    ]
