# Generated by Django 4.0.4 on 2022-05-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_db_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_user',
            old_name='usernam',
            new_name='username',
        ),
    ]
