# Generated by Django 4.0.4 on 2022-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_usernam_db_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_href',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='空', max_length=30, null=True)),
                ('url', models.CharField(blank=True, default='空', max_length=1000, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者')),
            ],
        ),
    ]
